[package]
name = "tsmatch"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/sahandevs/tsmatch"
description = "Collection of utility functions to find pattern in time series data"
license = "MIT"
readme = "./README.md"

[dependencies]
